/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hola */

#ifndef _Included_Hola
#define _Included_Hola
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hola
 * Method:    saluda
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hola_saluda
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
