/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Parametros */

#ifndef _Included_Parametros
#define _Included_Parametros
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Parametros
 * Method:    suma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Parametros_suma
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Parametros
 * Method:    pideTexto
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Parametros_pideTexto
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
